weakness_type_chart = {
    "psychic": {
        "1/2x": ["fighting", "psychic"],
        "1x": [
            "normal",
            "fire",
            "water",
            "electric",
            "grass",
            "ice",
            "poison",
            "ground",
            "flying",
            "rock",
            "dragon",
            "steel",
            "fairy",
        ],
        "2x": ["bug", "ghost", "dark"],
    },
    "normal": {
        "0x": ["ghost"],
        "1x": [
            "normal",
            "fire",
            "water",
            "electric",
            "grass",
            "ice",
            "poison",
            "ground",
            "flying",
            "psychic",
            "bug",
            "rock",
            "dragon",
            "dark",
            "steel",
            "fairy",
        ],
        "2x": ["fighting"],
    },
    "fire": {
        "1/2x": ["fire", "grass", "ice", "bug", "steel", "fairy"],
        "1x": [
            "normal",
            "electric",
            "fighting",
            "poison",
            "flying",
            "psychic",
            "ghost",
            "dragon",
            "dark",
        ],
        "2x": ["water", "ground", "rock"],
    },
    "water": {
        "1/2x": ["fire", "water", "ice", "steel"],
        "1x": [
            "normal",
            "fighting",
            "poison",
            "ground",
            "flying",
            "psychic",
            "bug",
            "rock",
            "ghost",
            "dragon",
            "dark",
            "fairy",
        ],
        "2x": ["electric", "grass"],
    },
    "electric": {
        "1/2x": ["electric", "flying", "steel"],
        "1x": [
            "normal",
            "fire",
            "water",
            "grass",
            "ice",
            "fighting",
            "poison",
            "psychic",
            "bug",
            "rock",
            "ghost",
            "dragon",
            "dark",
            "fairy",
        ],
        "2x": ["ground"],
    },
    "grass": {
        "1/2x": ["water", "electric", "grass", "ground"],
        "1x": [
            "normal",
            "fighting",
            "psychic",
            "rock",
            "ghost",
            "dragon",
            "dark",
            "steel",
            "fairy",
        ],
        "2x": ["fire", "ice", "poison", "flying", "bug"],
    },
    "ice": {
        "1/2x": ["ice"],
        "1x": [
            "normal",
            "water",
            "electric",
            "grass",
            "poison",
            "ground",
            "flying",
            "psychic",
            "bug",
            "ghost",
            "dragon",
            "dark",
            "fairy",
        ],
        "2x": ["fire", "fighting", "rock", "steel"],
    },
    "fighting": {
        "1/2x": ["bug", "rock", "dark"],
        "1x": [
            "normal",
            "fire",
            "water",
            "electric",
            "grass",
            "ice",
            "fighting",
            "poison",
            "ground",
            "ghost",
            "dragon",
            "steel",
        ],
        "2x": ["flying", "psychic", "fairy"],
    },
    "poison": {
        "1/2x": ["grass", "fighting", "poison", "bug", "fairy"],
        "1x": [
            "normal",
            "fire",
            "water",
            "electric",
            "ice",
            "flying",
            "rock",
            "ghost",
            "dragon",
            "dark",
            "steel",
        ],
        "2x": ["ground", "psychic"],
    },
    "ground": {
        "0x": ["electric"],
        "1/2x": ["poison", "rock"],
        "1x": [
            "normal",
            "fire",
            "fighting",
            "ground",
            "flying",
            "psychic",
            "bug",
            "ghost",
            "dragon",
            "dark",
            "steel",
            "fairy",
        ],
        "2x": ["water", "grass", "ice"],
    },
    "flying": {
        "0x": ["ground"],
        "1/2x": ["grass", "fighting", "bug"],
        "1x": [
            "normal",
            "fire",
            "water",
            "poison",
            "flying",
            "psychic",
            "ghost",
            "dragon",
            "dark",
            "steel",
            "fairy",
        ],
        "2x": ["electric", "ice", "rock"],
    },
    "bug": {
        "1/2x": ["grass", "fighting", "ground"],
        "1x": [
            "normal",
            "water",
            "electric",
            "ice",
            "poison",
            "psychic",
            "bug",
            "ghost",
            "dragon",
            "dark",
            "steel",
            "fairy",
        ],
        "2x": ["fire", "flying", "rock"],
    },
    "rock": {
        "1/2x": ["normal", "fire", "poison", "flying"],
        "1x": [
            "electric",
            "ice",
            "psychic",
            "bug",
            "rock",
            "ghost",
            "dragon",
            "dark",
            "fairy",
        ],
        "2x": ["water", "grass", "fighting", "ground", "steel"],
    },
    "ghost": {
        "0x": ["normal", "fighting"],
        "1/2x": ["poison", "bug"],
        "1x": [
            "fire",
            "water",
            "electric",
            "grass",
            "ice",
            "ground",
            "flying",
            "psychic",
            "rock",
            "dragon",
            "steel",
            "fairy",
        ],
        "2x": ["ghost", "dark"],
    },
    "dragon": {
        "1/2x": ["fire", "water", "electric", "grass"],
        "1x": [
            "normal",
            "fighting",
            "poison",
            "ground",
            "flying",
            "psychic",
            "bug",
            "rock",
            "ghost",
            "dark",
            "steel",
        ],
        "2x": ["ice", "dragon", "fairy"],
    },
    "dark": {
        "0x": ["psychic"],
        "1/2x": ["ghost", "dark"],
        "1x": [
            "normal",
            "fire",
            "water",
            "electric",
            "grass",
            "ice",
            "poison",
            "ground",
            "flying",
            "rock",
            "dragon",
            "steel",
        ],
        "2x": ["fighting", "bug", "fairy"],
    },
    "steel": {
        "0x": ["poison"],
        "1/2x": [
            "normal",
            "grass",
            "ice",
            "flying",
            "psychic",
            "bug",
            "rock",
            "dragon",
            "steel",
            "fairy",
        ],
        "1x": ["water", "electric", "ghost", "dark"],
        "2x": ["fire", "fighting", "ground"],
    },
    "fairy": {
        "0x": ["dragon"],
        "1/2x": ["fighting", "bug", "dark"],
        "1x": [
            "normal",
            "fire",
            "water",
            "electric",
            "grass",
            "ice",
            "ground",
            "flying",
            "psychic",
            "rock",
            "ghost",
            "fairy",
        ],
        "2x": ["poison", "steel"],
    },
    "bug_dark": {
        "0x": ["psychic"],
        "1/2x": ["grass", "ground", "ghost", "dark"],
        "1x": [
            "normal",
            "water",
            "electric",
            "ice",
            "fighting",
            "poison",
            "dragon",
            "steel",
        ],
        "2x": ["fire", "flying", "bug", "rock", "fairy"],
    },
    "bug_electric": {
        "1/2x": ["electric", "grass", "fighting", "steel"],
        "1x": [
            "normal",
            "water",
            "ice",
            "poison",
            "ground",
            "flying",
            "psychic",
            "bug",
            "ghost",
            "dragon",
            "dark",
            "fairy",
        ],
        "2x": ["fire", "rock"],
    },
    "bug_fairy": {
        "0x": ["dragon"],
        "1/2x": ["grass", "ground", "bug", "dark"],
        "1/4x": ["fighting"],
        "1x": ["normal", "water", "electric", "ice", "psychic", "ghost", "fairy"],
        "2x": ["fire", "poison", "flying", "rock", "steel"],
    },
    "bug_fighting": {
        "1/2x": ["grass", "fighting", "ground", "bug", "dark"],
        "1x": [
            "normal",
            "water",
            "electric",
            "ice",
            "poison",
            "rock",
            "ghost",
            "dragon",
            "steel",
        ],
        "2x": ["fire", "psychic", "fairy"],
        "4x": ["flying"],
    },
    "bug_fire": {
        "1/2x": ["ice", "fighting", "bug", "steel", "fairy"],
        "1/4x": ["grass"],
        "1x": [
            "normal",
            "fire",
            "electric",
            "poison",
            "ground",
            "psychic",
            "ghost",
            "dragon",
            "dark",
        ],
        "2x": ["water", "flying"],
        "4x": ["rock"],
    },
    "bug_flying": {
        "0x": ["ground"],
        "1/2x": ["bug"],
        "1/4x": ["grass", "fighting"],
        "1x": [
            "normal",
            "water",
            "poison",
            "psychic",
            "ghost",
            "dragon",
            "dark",
            "steel",
            "fairy",
        ],
        "2x": ["fire", "electric", "ice", "flying"],
        "4x": ["rock"],
    },
    "bug_ghost": {
        "0x": ["normal", "fighting"],
        "1/2x": ["grass", "poison", "ground", "bug"],
        "1x": ["water", "electric", "ice", "psychic", "dragon", "steel", "fairy"],
        "2x": ["fire", "flying", "rock", "ghost", "dark"],
    },
    "bug_grass": {
        "1/2x": ["water", "electric", "fighting"],
        "1/4x": ["grass", "ground"],
        "1x": ["normal", "psychic", "ghost", "dragon", "dark", "steel", "fairy"],
        "2x": ["ice", "poison", "bug", "rock"],
        "4x": ["fire", "flying"],
    },
    "bug_ground": {
        "0x": ["electric"],
        "1/2x": ["fighting", "poison", "ground"],
        "1x": [
            "normal",
            "grass",
            "psychic",
            "bug",
            "rock",
            "ghost",
            "dragon",
            "dark",
            "steel",
            "fairy",
        ],
        "2x": ["fire", "water", "ice", "flying"],
    },
    "bug_poison": {
        "1/2x": ["poison", "bug", "fairy"],
        "1/4x": ["grass", "fighting"],
        "1x": [
            "normal",
            "water",
            "electric",
            "ice",
            "ground",
            "ghost",
            "dragon",
            "dark",
            "steel",
        ],
        "2x": ["fire", "flying", "psychic", "rock"],
    },
    "bug_psychic": {
        "1/2x": ["grass", "ground", "psychic"],
        "1/4x": ["fighting"],
        "1x": [
            "normal",
            "water",
            "electric",
            "ice",
            "poison",
            "dragon",
            "steel",
            "fairy",
        ],
        "2x": ["fire", "flying", "bug", "rock", "ghost", "dark"],
    },
    "bug_rock": {
        "1/2x": ["normal", "poison"],
        "1x": [
            "fire",
            "electric",
            "grass",
            "ice",
            "fighting",
            "ground",
            "flying",
            "psychic",
            "bug",
            "ghost",
            "dragon",
            "dark",
            "fairy",
        ],
        "2x": ["water", "rock", "steel"],
    },
    "bug_steel": {
        "0x": ["poison"],
        "1/2x": ["normal", "ice", "psychic", "bug", "dragon", "steel", "fairy"],
        "1/4x": ["grass"],
        "1x": [
            "water",
            "electric",
            "fighting",
            "ground",
            "flying",
            "rock",
            "ghost",
            "dark",
        ],
        "4x": ["fire"],
    },
    "bug_water": {
        "1/2x": ["water", "ice", "fighting", "ground", "steel"],
        "1x": [
            "normal",
            "fire",
            "grass",
            "poison",
            "psychic",
            "bug",
            "ghost",
            "dragon",
            "dark",
            "fairy",
        ],
        "2x": ["electric", "flying", "rock"],
    },
    "dark_dragon": {
        "0x": ["psychic"],
        "1/2x": ["fire", "water", "electric", "grass", "ghost", "dark"],
        "1x": ["normal", "poison", "ground", "flying", "rock", "steel"],
        "2x": ["ice", "fighting", "bug", "dragon"],
        "4x": ["fairy"],
    },
    "dark_fairy": {
        "0x": ["psychic", "dragon"],
        "1/2x": ["ghost"],
        "1/4x": ["dark"],
        "1x": [
            "normal",
            "fire",
            "water",
            "electric",
            "grass",
            "ice",
            "fighting",
            "ground",
            "flying",
            "bug",
            "rock",
        ],
        "2x": ["poison", "steel", "fairy"],
    },
    "dark_fighting": {
        "0x": ["psychic"],
        "1/2x": ["rock", "ghost"],
        "1/4x": ["dark"],
        "1x": [
            "normal",
            "fire",
            "water",
            "electric",
            "grass",
            "ice",
            "poison",
            "ground",
            "bug",
            "dragon",
            "steel",
        ],
        "2x": ["fighting", "flying"],
        "4x": ["fairy"],
    },
    "dark_fire": {
        "0x": ["psychic"],
        "1/2x": ["fire", "grass", "ice", "ghost", "dark", "steel"],
        "1x": ["normal", "electric", "poison", "flying", "bug", "dragon", "fairy"],
        "2x": ["water", "fighting", "ground", "rock"],
    },
    "dark_flying": {
        "0x": ["ground", "psychic"],
        "1/2x": ["grass", "ghost", "dark"],
        "1x": [
            "normal",
            "fire",
            "water",
            "fighting",
            "poison",
            "flying",
            "bug",
            "dragon",
            "steel",
        ],
        "2x": ["electric", "ice", "rock", "fairy"],
    },
    "dark_ghost": {
        "0x": ["normal", "fighting", "psychic"],
        "1/2x": ["poison"],
        "1x": [
            "fire",
            "water",
            "electric",
            "grass",
            "ice",
            "ground",
            "flying",
            "bug",
            "rock",
            "ghost",
            "dragon",
            "dark",
            "steel",
        ],
        "2x": ["fairy"],
    },
    "dark_grass": {
        "0x": ["psychic"],
        "1/2x": ["water", "electric", "grass", "ground", "ghost", "dark"],
        "1x": ["normal", "rock", "dragon", "steel"],
        "2x": ["fire", "ice", "fighting", "poison", "flying", "fairy"],
        "4x": ["bug"],
    },
    "dark_ground": {
        "0x": ["electric", "psychic"],
        "1/2x": ["poison", "rock", "ghost", "dark"],
        "1x": ["normal", "fire", "ground", "flying", "dragon", "steel"],
        "2x": ["water", "grass", "ice", "fighting", "bug", "fairy"],
    },
    "dark_ice": {
        "0x": ["psychic"],
        "1/2x": ["ice", "ghost", "dark"],
        "1x": [
            "normal",
            "water",
            "electric",
            "grass",
            "poison",
            "ground",
            "flying",
            "dragon",
        ],
        "2x": ["fire", "bug", "rock", "steel", "fairy"],
        "4x": ["fighting"],
    },
    "dark_normal": {
        "0x": ["psychic", "ghost"],
        "1/2x": ["dark"],
        "1x": [
            "normal",
            "fire",
            "water",
            "electric",
            "grass",
            "ice",
            "poison",
            "ground",
            "flying",
            "rock",
            "dragon",
            "steel",
        ],
        "2x": ["bug", "fairy"],
        "4x": ["fighting"],
    },
    "dark_poison": {
        "0x": ["psychic"],
        "1/2x": ["grass", "poison", "ghost", "dark"],
        "1x": [
            "normal",
            "fire",
            "water",
            "electric",
            "ice",
            "fighting",
            "flying",
            "bug",
            "rock",
            "dragon",
            "steel",
            "fairy",
        ],
        "2x": ["ground"],
    },
    "dark_psychic": {
        "0x": ["psychic"],
        "1x": [
            "normal",
            "fire",
            "water",
            "electric",
            "grass",
            "ice",
            "fighting",
            "poison",
            "ground",
            "flying",
            "rock",
            "ghost",
            "dragon",
            "dark",
            "steel",
        ],
        "2x": ["fairy"],
        "4x": ["bug"],
    },
    "dark_steel": {
        "0x": ["poison", "psychic"],
        "1/2x": [
            "normal",
            "grass",
            "ice",
            "flying",
            "rock",
            "ghost",
            "dragon",
            "dark",
            "steel",
        ],
        "1x": ["water", "electric", "bug", "fairy"],
        "2x": ["fire", "ground"],
        "4x": ["fighting"],
    },
    "dragon_dark": {
        "0x": ["psychic"],
        "1/2x": ["fire", "water", "electric", "grass", "ghost", "dark"],
        "1x": ["normal", "poison", "ground", "flying", "rock", "steel"],
        "2x": ["ice", "fighting", "bug", "dragon"],
        "4x": ["fairy"],
    },
    "dragon_electric": {
        "1/2x": ["fire", "water", "grass", "flying", "steel"],
        "1/4x": ["electric"],
        "1x": [
            "normal",
            "fighting",
            "poison",
            "psychic",
            "bug",
            "rock",
            "ghost",
            "dark",
        ],
        "2x": ["ice", "ground", "dragon", "fairy"],
    },
    "dragon_fairy": {
        "0x": ["dragon"],
        "1/2x": ["fire", "water", "electric", "grass", "fighting", "bug", "dark"],
        "1x": ["normal", "ground", "flying", "psychic", "rock", "ghost"],
        "2x": ["ice", "poison", "steel", "fairy"],
    },
    "dragon_fighting": {
        "1/2x": ["fire", "water", "electric", "grass", "bug", "rock", "dark"],
        "1x": ["normal", "fighting", "poison", "ground", "ghost", "steel"],
        "2x": ["ice", "flying", "psychic", "dragon"],
        "4x": ["fairy"],
    },
    "dragon_fire": {
        "1/2x": ["electric", "bug", "steel"],
        "1/4x": ["fire", "grass"],
        "1x": [
            "normal",
            "water",
            "ice",
            "fighting",
            "poison",
            "flying",
            "psychic",
            "ghost",
            "dark",
            "fairy",
        ],
        "2x": ["ground", "rock", "dragon"],
    },
    "dragon_flying": {
        "0x": ["ground"],
        "1/2x": ["fire", "water", "fighting", "bug"],
        "1/4x": ["grass"],
        "1x": [
            "normal",
            "electric",
            "poison",
            "flying",
            "psychic",
            "ghost",
            "dark",
            "steel",
        ],
        "2x": ["rock", "dragon", "fairy"],
        "4x": ["ice"],
    },
    "dragon_ghost": {
        "0x": ["normal", "fighting"],
        "1/2x": ["fire", "water", "electric", "grass", "poison", "bug"],
        "1x": ["ground", "flying", "psychic", "rock", "steel"],
        "2x": ["ice", "ghost", "dragon", "dark", "fairy"],
    },
    "dragon_ground": {
        "0x": ["electric"],
        "1/2x": ["fire", "poison", "rock"],
        "1x": [
            "normal",
            "water",
            "grass",
            "fighting",
            "ground",
            "flying",
            "psychic",
            "bug",
            "ghost",
            "dark",
            "steel",
        ],
        "2x": ["dragon", "fairy"],
        "4x": ["ice"],
    },
    "dragon_ice": {
        "1/2x": ["water", "electric", "grass"],
        "1x": [
            "normal",
            "fire",
            "ice",
            "poison",
            "ground",
            "flying",
            "psychic",
            "bug",
            "ghost",
            "dark",
        ],
        "2x": ["fighting", "rock", "dragon", "steel", "fairy"],
    },
    "dragon_normal": {
        "0x": ["ghost"],
        "1/2x": ["fire", "water", "electric", "grass"],
        "1x": [
            "normal",
            "poison",
            "ground",
            "flying",
            "psychic",
            "bug",
            "rock",
            "dark",
            "steel",
        ],
        "2x": ["ice", "fighting", "dragon", "fairy"],
    },
    "dragon_psychic": {
        "1/2x": ["fire", "water", "electric", "grass", "fighting", "psychic"],
        "1x": ["normal", "poison", "ground", "flying", "rock", "steel"],
        "2x": ["ice", "bug", "ghost", "dragon", "dark", "fairy"],
    },
    "dragon_water": {
        "1/2x": ["steel"],
        "1/4x": ["fire", "water"],
        "1x": [
            "normal",
            "electric",
            "grass",
            "ice",
            "fighting",
            "poison",
            "ground",
            "flying",
            "psychic",
            "bug",
            "rock",
            "ghost",
            "dark",
        ],
        "2x": ["dragon", "fairy"],
    },
    "electric_dark": {
        "0x": ["psychic"],
        "1/2x": ["electric", "flying", "ghost", "dark", "steel"],
        "1x": ["normal", "fire", "water", "grass", "ice", "poison", "rock", "dragon"],
        "2x": ["fighting", "ground", "bug", "fairy"],
    },
    "electric_dragon": {
        "1/2x": ["fire", "water", "grass", "flying", "steel"],
        "1/4x": ["electric"],
        "1x": [
            "normal",
            "fighting",
            "poison",
            "psychic",
            "bug",
            "rock",
            "ghost",
            "dark",
        ],
        "2x": ["ice", "ground", "dragon", "fairy"],
    },
    "electric_fairy": {
        "0x": ["dragon"],
        "1/2x": ["electric", "fighting", "flying", "bug", "dark"],
        "1x": [
            "normal",
            "fire",
            "water",
            "grass",
            "ice",
            "psychic",
            "rock",
            "ghost",
            "steel",
            "fairy",
        ],
        "2x": ["poison", "ground"],
    },
    "electric_fighting": {
        "1/2x": ["electric", "bug", "rock", "dark", "steel"],
        "1x": [
            "normal",
            "fire",
            "water",
            "grass",
            "ice",
            "fighting",
            "poison",
            "flying",
            "ghost",
            "dragon",
        ],
        "2x": ["ground", "psychic", "fairy"],
    },
    "electric_fire": {
        "1/2x": ["fire", "electric", "grass", "ice", "flying", "bug", "fairy"],
        "1/4x": ["steel"],
        "1x": ["normal", "fighting", "poison", "psychic", "ghost", "dragon", "dark"],
        "2x": ["water", "rock"],
        "4x": ["ground"],
    },
    "electric_flying": {
        "0x": ["ground"],
        "1/2x": ["grass", "fighting", "flying", "bug", "steel"],
        "1x": [
            "normal",
            "fire",
            "water",
            "electric",
            "poison",
            "psychic",
            "ghost",
            "dragon",
            "dark",
            "fairy",
        ],
        "2x": ["ice", "rock"],
    },
    "electric_ghost": {
        "0x": ["normal", "fighting"],
        "1/2x": ["electric", "poison", "flying", "bug", "steel"],
        "1x": ["fire", "water", "grass", "ice", "psychic", "rock", "dragon", "fairy"],
        "2x": ["ground", "ghost", "dark"],
    },
    "electric_grass": {
        "1/2x": ["water", "grass", "steel"],
        "1/4x": ["electric"],
        "1x": [
            "normal",
            "flying",
            "fighting",
            "ground",
            "rock",
            "psychic",
            "ghost",
            "dark",
            "dragon",
            "fairy",
        ],
        "2x": ["fire", "poison", "ice", "bug"],
    },
    "electric_ground": {
        "0x": ["electric"],
        "1/2x": ["poison", "flying", "rock", "steel"],
        "1x": [
            "normal",
            "fire",
            "fighting",
            "psychic",
            "bug",
            "ghost",
            "dragon",
            "dark",
            "fairy",
        ],
        "2x": ["water", "grass", "ice", "ground"],
    },
    "electric_ice": {
        "1/2x": ["electric", "ice", "flying"],
        "1x": [
            "normal",
            "water",
            "grass",
            "poison",
            "psychic",
            "bug",
            "ghost",
            "dragon",
            "dark",
            "steel",
            "fairy",
        ],
        "2x": ["fire", "fighting", "ground", "rock"],
    },
    "electric_normal": {
        "0x": ["ghost"],
        "1/2x": ["electric", "flying", "steel"],
        "1x": [
            "normal",
            "fire",
            "water",
            "grass",
            "ice",
            "poison",
            "psychic",
            "bug",
            "rock",
            "dragon",
            "dark",
            "fairy",
        ],
        "2x": ["fighting", "ground"],
    },
    "electric_poison": {
        "1/2x": [
            "electric",
            "grass",
            "fighting",
            "poison",
            "flying",
            "bug",
            "steel",
            "fairy",
        ],
        "1x": ["normal", "fire", "water", "ice", "rock", "ghost", "dragon", "dark"],
        "2x": ["psychic"],
        "4x": ["ground"],
    },
    "electric_psychic": {
        "1/2x": ["electric", "fighting", "flying", "psychic", "steel"],
        "1x": [
            "normal",
            "fire",
            "water",
            "grass",
            "ice",
            "poison",
            "rock",
            "dragon",
            "fairy",
        ],
        "2x": ["ground", "bug", "ghost", "dark"],
    },
    "electric_steel": {
        "0x": ["poison"],
        "1/2x": [
            "normal",
            "electric",
            "grass",
            "ice",
            "psychic",
            "bug",
            "rock",
            "dragon",
            "fairy",
        ],
        "1/4x": ["flying", "steel"],
        "1x": ["water", "ghost", "dark"],
        "2x": ["fire", "fighting"],
        "4x": ["ground"],
    },
    "electric_water": {
        "1/2x": ["fire", "water", "ice", "flying"],
        "1/4x": ["steel"],
        "1x": [
            "normal",
            "electric",
            "fighting",
            "poison",
            "psychic",
            "bug",
            "rock",
            "ghost",
            "dragon",
            "dark",
            "fairy",
        ],
        "2x": ["grass", "ground"],
    },
    "fairy_fighting": {
        "0x": ["dragon"],
        "1/2x": ["fighting", "rock"],
        "1/4x": ["bug", "dark"],
        "1x": [
            "normal",
            "fire",
            "water",
            "electric",
            "grass",
            "ice",
            "ground",
            "ghost",
        ],
        "2x": ["poison", "flying", "psychic", "steel", "fairy"],
    },
    "fairy_flying": {
        "0x": ["ground", "dragon"],
        "1/2x": ["grass", "dark"],
        "1/4x": ["fighting", "bug"],
        "1x": ["normal", "fire", "water", "flying", "psychic", "ghost", "fairy"],
        "2x": ["electric", "ice", "poison", "rock", "steel"],
    },
    "fairy_psychic": {
        "0x": ["dragon"],
        "1/2x": ["psychic"],
        "1/4x": ["fighting"],
        "1x": [
            "normal",
            "fire",
            "water",
            "electric",
            "grass",
            "ice",
            "ground",
            "flying",
            "bug",
            "rock",
            "dark",
            "fairy",
        ],
        "2x": ["poison", "ghost", "steel"],
    },
    "fairy_steel": {
        "0x": ["poison", "dragon"],
        "1/2x": [
            "normal",
            "grass",
            "ice",
            "flying",
            "psychic",
            "rock",
            "dark",
            "fairy",
        ],
        "1/4x": ["bug"],
        "1x": ["water", "electric", "fighting", "ghost", "steel"],
        "2x": ["fire", "ground"],
    },
    "fighting_dark": {
        "0x": ["psychic"],
        "1/2x": ["rock", "ghost"],
        "1/4x": ["dark"],
        "1x": [
            "normal",
            "fire",
            "water",
            "electric",
            "grass",
            "ice",
            "poison",
            "ground",
            "bug",
            "dragon",
            "steel",
        ],
        "2x": ["fighting", "flying"],
        "4x": ["fairy"],
    },
    "fighting_dragon": {
        "1/2x": ["fire", "water", "electric", "grass", "bug", "rock", "dark"],
        "1x": ["normal", "fighting", "poison", "ground", "ghost", "steel"],
        "2x": ["ice", "flying", "psychic", "dragon"],
        "4x": ["fairy"],
    },
    "fighting_electric": {
        "1/2x": ["electric", "bug", "rock", "dark", "steel"],
        "1x": [
            "normal",
            "fire",
            "water",
            "grass",
            "ice",
            "fighting",
            "poison",
            "flying",
            "ghost",
            "dragon",
        ],
        "2x": ["ground", "psychic", "fairy"],
    },
    "fighting_fire": {
        "1/2x": ["fire", "grass", "ice", "dark", "steel"],
        "1/4x": ["bug"],
        "1x": [
            "normal",
            "electric",
            "fighting",
            "poison",
            "rock",
            "ghost",
            "dragon",
            "fairy",
        ],
        "2x": ["water", "ground", "flying", "psychic"],
    },
    "fighting_flying": {
        "0x": ["ground"],
        "1/2x": ["grass", "fighting", "dark"],
        "1/4x": ["bug"],
        "1x": ["normal", "fire", "water", "poison", "rock", "ghost", "dragon", "steel"],
        "2x": ["electric", "ice", "flying", "psychic", "fairy"],
    },
    "fighting_ghost": {
        "0x": ["normal", "fighting"],
        "1/2x": ["poison", "rock"],
        "1/4x": ["bug"],
        "1x": [
            "fire",
            "water",
            "electric",
            "grass",
            "ice",
            "ground",
            "dragon",
            "dark",
            "steel",
        ],
        "2x": ["flying", "psychic", "ghost", "fairy"],
    },
    "fighting_ice": {
        "1/2x": ["ice", "bug", "dark"],
        "1x": [
            "normal",
            "water",
            "electric",
            "grass",
            "poison",
            "ground",
            "rock",
            "ghost",
            "dragon",
        ],
        "2x": ["fire", "fighting", "flying", "psychic", "steel", "fairy"],
    },
    "fighting_poison": {
        "1/2x": ["grass", "fighting", "poison", "rock", "dark"],
        "1/4x": ["bug"],
        "1x": [
            "normal",
            "fire",
            "water",
            "electric",
            "ice",
            "ghost",
            "dragon",
            "steel",
            "fairy",
        ],
        "2x": ["ground", "flying"],
        "4x": ["psychic"],
    },
    "fighting_psychic": {
        "1/2x": ["fighting", "rock"],
        "1x": [
            "normal",
            "fire",
            "water",
            "electric",
            "grass",
            "ice",
            "poison",
            "ground",
            "psychic",
            "bug",
            "dragon",
            "dark",
            "steel",
        ],
        "2x": ["flying", "ghost", "fairy"],
    },
    "fighting_steel": {
        "0x": ["poison"],
        "1/2x": ["normal", "grass", "ice", "dragon", "dark", "steel"],
        "1/4x": ["bug", "rock"],
        "1x": ["water", "electric", "flying", "psychic", "ghost", "fairy"],
        "2x": ["fire", "fighting", "ground"],
    },
    "fighting_water": {
        "1/2x": ["fire", "water", "ice", "bug", "rock", "dark", "steel"],
        "1x": ["normal", "fighting", "poison", "ground", "ghost", "dragon"],
        "2x": ["electric", "grass", "flying", "psychic", "fairy"],
    },
    "fire_bug": {
        "1/2x": ["ice", "fighting", "bug", "steel", "fairy"],
        "1/4x": ["grass"],
        "1x": [
            "normal",
            "fire",
            "electric",
            "poison",
            "ground",
            "psychic",
            "ghost",
            "dragon",
            "dark",
        ],
        "2x": ["water", "flying"],
        "4x": ["rock"],
    },
    "fire_dark": {
        "0x": ["psychic"],
        "1/2x": ["fire", "grass", "ice", "ghost", "dark", "steel"],
        "1x": ["normal", "electric", "poison", "flying", "bug", "dragon", "fairy"],
        "2x": ["water", "fighting", "ground", "rock"],
    },
    "fire_dragon": {
        "1/2x": ["electric", "bug", "steel"],
        "1/4x": ["fire", "grass"],
        "1x": [
            "normal",
            "water",
            "ice",
            "fighting",
            "poison",
            "flying",
            "psychic",
            "ghost",
            "dark",
            "fairy",
        ],
        "2x": ["ground", "rock", "dragon"],
    },
    "fire_fighting": {
        "1/2x": ["fire", "grass", "ice", "dark", "steel"],
        "1/4x": ["bug"],
        "1x": [
            "normal",
            "electric",
            "fighting",
            "poison",
            "rock",
            "ghost",
            "dragon",
            "fairy",
        ],
        "2x": ["water", "ground", "flying", "psychic"],
    },
    "fire_flying": {
        "0x": ["ground"],
        "1/2x": ["fire", "fighting", "steel", "fairy"],
        "1/4x": ["grass", "bug"],
        "1x": [
            "normal",
            "ice",
            "poison",
            "flying",
            "psychic",
            "ghost",
            "dragon",
            "dark",
        ],
        "2x": ["water", "electric"],
        "4x": ["rock"],
    },
    "fire_ghost": {
        "0x": ["normal", "fighting"],
        "1/2x": ["fire", "grass", "ice", "poison", "steel", "fairy"],
        "1/4x": ["bug"],
        "1x": ["electric", "flying", "psychic", "dragon"],
        "2x": ["water", "ground", "rock", "ghost", "dark"],
    },
    "fire_ground": {
        "0x": ["electric"],
        "1/2x": ["fire", "poison", "bug", "steel", "fairy"],
        "1x": [
            "normal",
            "grass",
            "ice",
            "fighting",
            "flying",
            "psychic",
            "rock",
            "ghost",
            "dragon",
            "dark",
        ],
        "2x": ["ground"],
        "4x": ["water"],
    },
    "fire_normal": {
        "0x": ["ghost"],
        "1/2x": ["fire", "grass", "ice", "bug", "steel", "fairy"],
        "1x": ["normal", "electric", "poison", "flying", "psychic", "dragon", "dark"],
        "2x": ["water", "fighting", "ground", "rock"],
    },
    "fire_poison": {
        "1/2x": ["fire", "ice", "fighting", "poison", "steel"],
        "1/4x": ["grass", "bug", "fairy"],
        "1x": ["normal", "electric", "flying", "ghost", "dragon", "dark"],
        "2x": ["water", "psychic", "rock"],
        "4x": ["ground"],
    },
    "fire_psychic": {
        "1/2x": ["fire", "grass", "ice", "fighting", "psychic", "steel", "fairy"],
        "1x": ["normal", "electric", "poison", "flying", "bug", "dragon"],
        "2x": ["water", "ground", "rock", "ghost", "dark"],
    },
    "fire_rock": {
        "1/2x": ["normal", "ice", "poison", "flying", "bug", "fairy"],
        "1/4x": ["fire"],
        "1x": ["electric", "grass", "psychic", "ghost", "dragon", "dark", "steel"],
        "2x": ["fighting", "rock"],
        "4x": ["water", "ground"],
    },
    "fire_steel": {
        "0x": ["poison"],
        "1/2x": ["normal", "flying", "psychic", "dragon"],
        "1/4x": ["grass", "ice", "bug", "steel", "fairy"],
        "1x": ["fire", "electric", "rock", "ghost", "dark"],
        "2x": ["water", "fighting"],
        "4x": ["ground"],
    },
    "fire_water": {
        "1/2x": ["bug", "fairy"],
        "1/4x": ["fire", "ice", "steel"],
        "1x": [
            "normal",
            "water",
            "grass",
            "fighting",
            "poison",
            "flying",
            "psychic",
            "ghost",
            "dragon",
            "dark",
        ],
        "2x": ["electric", "ground", "rock"],
    },
    "flying_dark": {
        "0x": ["ground", "psychic"],
        "1/2x": ["grass", "ghost", "dark"],
        "1x": [
            "normal",
            "fire",
            "water",
            "fighting",
            "poison",
            "flying",
            "bug",
            "dragon",
            "steel",
        ],
        "2x": ["electric", "ice", "rock", "fairy"],
    },
    "flying_dragon": {
        "0x": ["ground"],
        "1/2x": ["fire", "water", "fighting", "bug"],
        "1/4x": ["grass"],
        "1x": [
            "normal",
            "electric",
            "poison",
            "flying",
            "psychic",
            "ghost",
            "dark",
            "steel",
        ],
        "2x": ["rock", "dragon", "fairy"],
        "4x": ["ice"],
    },
    "flying_fighting": {
        "0x": ["ground"],
        "1/2x": ["grass", "fighting", "dark"],
        "1/4x": ["bug"],
        "1x": ["normal", "fire", "water", "poison", "rock", "ghost", "dragon", "steel"],
        "2x": ["electric", "ice", "flying", "psychic", "fairy"],
    },
    "flying_steel": {
        "0x": ["poison", "ground"],
        "1/2x": ["normal", "flying", "psychic", "dragon", "steel", "fairy"],
        "1/4x": ["grass", "bug"],
        "1x": ["water", "ice", "fighting", "rock", "ghost", "dark"],
        "2x": ["fire", "electric"],
    },
    "flying_water": {
        "0x": ["ground"],
        "1/2x": ["fire", "water", "fighting", "bug", "steel"],
        "1x": [
            "normal",
            "grass",
            "ice",
            "poison",
            "flying",
            "psychic",
            "ghost",
            "dragon",
            "dark",
            "fairy",
        ],
        "2x": ["rock"],
        "4x": ["electric"],
    },
    "ghost_dark": {
        "0x": ["normal", "fighting", "psychic"],
        "1/2x": ["poison"],
        "1x": [
            "fire",
            "water",
            "electric",
            "grass",
            "ice",
            "ground",
            "flying",
            "bug",
            "rock",
            "ghost",
            "dragon",
            "dark",
            "steel",
        ],
        "2x": ["fairy"],
    },
    "ghost_dragon": {
        "0x": ["normal", "fighting"],
        "1/2x": ["fire", "water", "electric", "grass", "poison", "bug"],
        "1x": ["ground", "flying", "psychic", "rock", "steel"],
        "2x": ["ice", "ghost", "dragon", "dark", "fairy"],
    },
    "ghost_fairy": {
        "0x": ["normal", "fighting", "dragon"],
        "1/4x": ["bug"],
        "1x": [
            "fire",
            "water",
            "electric",
            "grass",
            "ice",
            "poison",
            "ground",
            "flying",
            "psychic",
            "rock",
            "dark",
            "fairy",
        ],
        "2x": ["ghost", "steel"],
    },
    "ghost_fire": {
        "0x": ["normal", "fighting"],
        "1/2x": ["fire", "grass", "ice", "poison", "steel", "fairy"],
        "1/4x": ["bug"],
        "1x": ["electric", "flying", "psychic", "dragon"],
        "2x": ["water", "ground", "rock", "ghost", "dark"],
    },
    "ghost_flying": {
        "0x": ["normal", "fighting", "ground"],
        "1/2x": ["grass", "poison"],
        "1/4x": ["bug"],
        "1x": ["fire", "water", "flying", "psychic", "dragon", "steel", "fairy"],
        "2x": ["electric", "ice", "rock", "ghost", "dark"],
    },
    "ghost_grass": {
        "0x": ["normal", "fighting"],
        "1/2x": ["water", "electric", "grass", "ground"],
        "1x": ["poison", "psychic", "bug", "rock", "dragon", "steel", "fairy"],
        "2x": ["fire", "ice", "flying", "ghost", "dark"],
    },
    "ghost_ground": {
        "0x": ["normal", "electric", "fighting"],
        "1/2x": ["bug", "rock"],
        "1/4x": ["poison"],
        "1x": ["fire", "ground", "flying", "psychic", "dragon", "steel", "fairy"],
        "2x": ["water", "grass", "ice", "ghost", "dark"],
    },
    "ghost_poison": {
        "0x": ["normal", "fighting"],
        "1/2x": ["grass", "fairy"],
        "1/4x": ["poison", "bug"],
        "1x": ["fire", "water", "electric", "ice", "flying", "rock", "dragon", "steel"],
        "2x": ["ground", "psychic", "ghost", "dark"],
    },
    "grass_dark": {
        "0x": ["psychic"],
        "1/2x": ["water", "electric", "grass", "ground", "ghost", "dark"],
        "1x": ["normal", "rock", "dragon", "steel"],
        "2x": ["fire", "ice", "fighting", "poison", "flying", "fairy"],
        "4x": ["bug"],
    },
    "grass_dragon": {
        "1/2x": ["ground"],
        "1/4x": ["water", "electric", "grass"],
        "1x": [
            "normal",
            "fire",
            "fighting",
            "psychic",
            "rock",
            "ghost",
            "dark",
            "steel",
        ],
        "2x": ["poison", "flying", "bug", "dragon", "fairy"],
        "4x": ["ice"],
    },
    "grass_fairy": {
        "0x": ["dragon"],
        "1/2x": ["water", "electric", "grass", "fighting", "ground", "dark"],
        "1x": ["normal", "psychic", "bug", "rock", "ghost", "fairy"],
        "2x": ["fire", "ice", "flying", "steel"],
        "4x": ["poison"],
    },
    "grass_fighting": {
        "1/2x": ["water", "electric", "grass", "ground", "rock", "dark"],
        "1x": ["normal", "fighting", "bug", "ghost", "dragon", "steel"],
        "2x": ["fire", "ice", "poison", "psychic", "fairy"],
        "4x": ["flying"],
    },
    "grass_fire": {
        "1/2x": ["electric", "steel", "fairy"],
        "1/4x": ["grass"],
        "1x": [
            "normal",
            "fire",
            "water",
            "ice",
            "fighting",
            "ground",
            "psychic",
            "bug",
            "ghost",
            "dragon",
            "dark",
        ],
        "2x": ["poison", "flying", "rock"],
    },
    "grass_flying": {
        "0x": ["ground"],
        "1/2x": ["water", "fighting"],
        "1/4x": ["grass"],
        "1x": [
            "normal",
            "electric",
            "psychic",
            "bug",
            "ghost",
            "dragon",
            "dark",
            "steel",
            "fairy",
        ],
        "2x": ["fire", "poison", "flying", "rock"],
        "4x": ["ice"],
    },
    "grass_ghost": {
        "0x": ["normal", "fighting"],
        "1/2x": ["water", "electric", "grass", "ground"],
        "1x": ["poison", "psychic", "bug", "rock", "dragon", "steel", "fairy"],
        "2x": ["fire", "ice", "flying", "ghost", "dark"],
    },
    "grass_ground": {
        "0x": ["electric"],
        "1/2x": ["ground", "rock"],
        "1x": [
            "normal",
            "water",
            "grass",
            "fighting",
            "poison",
            "psychic",
            "ghost",
            "dragon",
            "dark",
            "steel",
            "fairy",
        ],
        "2x": ["fire", "flying", "bug"],
        "4x": ["ice"],
    },
    "grass_ice": {
        "1/2x": ["water", "electric", "grass", "ground"],
        "1x": ["normal", "ice", "psychic", "ghost", "dragon", "dark", "fairy"],
        "2x": ["fighting", "poison", "flying", "bug", "rock", "steel"],
        "4x": ["fire"],
    },
    "grass_normal": {
        "0x": ["ghost"],
        "1/2x": ["water", "electric", "grass", "ground"],
        "1x": ["normal", "psychic", "rock", "dragon", "dark", "steel", "fairy"],
        "2x": ["fire", "ice", "fighting", "poison", "flying", "bug"],
    },
    "grass_poison": {
        "1/2x": ["water", "electric", "fighting", "fairy"],
        "1/4x": ["grass"],
        "1x": [
            "normal",
            "poison",
            "ground",
            "bug",
            "rock",
            "ghost",
            "dragon",
            "dark",
            "steel",
        ],
        "2x": ["fire", "ice", "flying", "psychic"],
    },
    "grass_psychic": {
        "1/2x": ["water", "electric", "grass", "fighting", "ground", "psychic"],
        "1x": ["normal", "rock", "dragon", "steel", "fairy"],
        "2x": ["fire", "ice", "poison", "flying", "ghost", "dark"],
        "4x": ["bug"],
    },
    "grass_rock": {
        "1/2x": ["normal", "electric"],
        "1x": [
            "fire",
            "water",
            "grass",
            "poison",
            "ground",
            "flying",
            "psychic",
            "rock",
            "ghost",
            "dragon",
            "dark",
            "fairy",
        ],
        "2x": ["ice", "fighting", "bug", "steel"],
    },
    "grass_steel": {
        "0x": ["poison"],
        "1/2x": [
            "normal",
            "water",
            "electric",
            "psychic",
            "rock",
            "dragon",
            "steel",
            "fairy",
        ],
        "1/4x": ["grass"],
        "1x": ["ice", "ground", "flying", "bug", "ghost", "dark"],
        "2x": ["fighting"],
        "4x": ["fire"],
    },
    "grass_water": {
        "1/2x": ["ground", "steel"],
        "1/4x": ["water"],
        "1x": [
            "normal",
            "fire",
            "electric",
            "grass",
            "ice",
            "fighting",
            "psychic",
            "rock",
            "ghost",
            "dragon",
            "dark",
            "fairy",
        ],
        "2x": ["poison", "flying", "bug"],
    },
    "ground_dark": {
        "0x": ["electric", "psychic"],
        "1/2x": ["poison", "rock", "ghost", "dark"],
        "1x": ["normal", "fire", "ground", "flying", "dragon", "steel"],
        "2x": ["water", "grass", "ice", "fighting", "bug", "fairy"],
    },
    "ground_dragon": {
        "0x": ["electric"],
        "1/2x": ["fire", "poison", "rock"],
        "1x": [
            "normal",
            "water",
            "grass",
            "fighting",
            "ground",
            "flying",
            "psychic",
            "bug",
            "ghost",
            "dark",
            "steel",
        ],
        "2x": ["dragon", "fairy"],
        "4x": ["ice"],
    },
    "ground_electric": {
        "0x": ["electric"],
        "1/2x": ["poison", "flying", "rock", "steel"],
        "1x": [
            "normal",
            "fire",
            "fighting",
            "psychic",
            "bug",
            "ghost",
            "dragon",
            "dark",
            "fairy",
        ],
        "2x": ["water", "grass", "ice", "ground"],
    },
    "ground_fighting": {
        "0x": ["electric"],
        "1/2x": ["poison", "bug", "dark"],
        "1/4x": ["rock"],
        "1x": ["normal", "fire", "fighting", "ground", "ghost", "dragon", "steel"],
        "2x": ["water", "grass", "ice", "flying", "psychic", "fairy"],
    },
    "ground_fire": {
        "0x": ["electric"],
        "1/2x": ["fire", "poison", "bug", "steel", "fairy"],
        "1x": [
            "normal",
            "grass",
            "ice",
            "fighting",
            "flying",
            "psychic",
            "rock",
            "ghost",
            "dragon",
            "dark",
        ],
        "2x": ["ground"],
        "4x": ["water"],
    },
    "ground_flying": {
        "0x": ["electric", "ground"],
        "1/2x": ["fighting", "poison", "bug"],
        "1x": [
            "normal",
            "fire",
            "grass",
            "flying",
            "psychic",
            "rock",
            "ghost",
            "dragon",
            "dark",
            "steel",
            "fairy",
        ],
        "2x": ["water"],
        "4x": ["ice"],
    },
    "ground_ghost": {
        "0x": ["normal", "electric", "fighting"],
        "1/2x": ["bug", "rock"],
        "1/4x": ["poison"],
        "1x": ["fire", "ground", "flying", "psychic", "dragon", "steel", "fairy"],
        "2x": ["water", "grass", "ice", "ghost", "dark"],
    },
    "ground_grass": {
        "0x": ["electric"],
        "1/2x": ["ground", "rock"],
        "1x": [
            "normal",
            "water",
            "grass",
            "fighting",
            "poison",
            "psychic",
            "ghost",
            "dragon",
            "dark",
            "steel",
            "fairy",
        ],
        "2x": ["fire", "flying", "bug"],
        "4x": ["ice"],
    },
    "ground_normal": {
        "0x": ["electric", "ghost"],
        "1/2x": ["poison", "rock"],
        "1x": [
            "normal",
            "fire",
            "ground",
            "flying",
            "psychic",
            "bug",
            "dragon",
            "dark",
            "steel",
            "fairy",
        ],
        "2x": ["water", "grass", "ice", "fighting"],
    },
    "ground_psychic": {
        "0x": ["electric"],
        "1/2x": ["fighting", "poison", "psychic", "rock"],
        "1x": ["normal", "fire", "ground", "flying", "dragon", "steel", "fairy"],
        "2x": ["water", "grass", "ice", "bug", "ghost", "dark"],
    },
    "ground_rock": {
        "0x": ["electric"],
        "1/2x": ["normal", "fire", "flying", "rock"],
        "1/4x": ["poison"],
        "1x": ["psychic", "bug", "ghost", "dragon", "dark", "fairy"],
        "2x": ["ice", "fighting", "ground", "steel"],
        "4x": ["water", "grass"],
    },
    "ground_steel": {
        "0x": ["electric", "poison"],
        "1/2x": ["normal", "flying", "psychic", "bug", "dragon", "steel", "fairy"],
        "1/4x": ["rock"],
        "1x": ["grass", "ice", "ghost", "dark"],
        "2x": ["fire", "water", "fighting", "ground"],
    },
    "ice_bug": {
        "1/2x": ["grass", "ice", "ground"],
        "1x": [
            "normal",
            "water",
            "electric",
            "fighting",
            "poison",
            "psychic",
            "bug",
            "ghost",
            "dragon",
            "dark",
            "fairy",
        ],
        "2x": ["flying", "steel"],
        "4x": ["fire", "rock"],
    },
    "ice_fairy": {
        "0x": ["dragon"],
        "1/2x": ["ice", "bug", "dark"],
        "1x": [
            "normal",
            "water",
            "electric",
            "grass",
            "fighting",
            "ground",
            "flying",
            "psychic",
            "ghost",
            "fairy",
        ],
        "2x": ["fire", "poison", "rock"],
        "4x": ["steel"],
    },
    "ice_fire": {
        "1/2x": ["grass", "bug", "fairy"],
        "1/4x": ["ice"],
        "1x": [
            "normal",
            "fire",
            "electric",
            "poison",
            "flying",
            "psychic",
            "ghost",
            "dragon",
            "dark",
            "steel",
        ],
        "2x": ["water", "fighting", "ground"],
        "4x": ["rock"],
    },
    "ice_flying": {
        "0x": ["ground"],
        "1/2x": ["grass", "bug"],
        "1x": [
            "normal",
            "water",
            "ice",
            "fighting",
            "poison",
            "flying",
            "psychic",
            "ghost",
            "dragon",
            "dark",
            "fairy",
        ],
        "2x": ["fire", "electric", "steel"],
        "4x": ["rock"],
    },
    "ice_ghost": {
        "0x": ["normal", "fighting"],
        "1/2x": ["ice", "poison", "bug"],
        "1x": [
            "water",
            "electric",
            "grass",
            "ground",
            "flying",
            "psychic",
            "dragon",
            "fairy",
        ],
        "2x": ["fire", "rock", "ghost", "dark", "steel"],
    },
    "ice_ground": {
        "0x": ["electric"],
        "1/2x": ["poison"],
        "1x": [
            "normal",
            "ice",
            "ground",
            "flying",
            "psychic",
            "bug",
            "rock",
            "ghost",
            "dragon",
            "dark",
            "fairy",
        ],
        "2x": ["fire", "water", "grass", "fighting", "steel"],
    },
    "ice_psychic": {
        "1/2x": ["ice", "psychic"],
        "1x": [
            "normal",
            "water",
            "electric",
            "grass",
            "fighting",
            "poison",
            "ground",
            "flying",
            "dragon",
            "fairy",
        ],
        "2x": ["fire", "bug", "rock", "ghost", "dark", "steel"],
    },
    "ice_rock": {
        "1/2x": ["normal", "ice", "poison", "flying"],
        "1x": [
            "fire",
            "electric",
            "psychic",
            "bug",
            "ghost",
            "dragon",
            "dark",
            "fairy",
        ],
        "2x": ["water", "grass", "ground", "rock"],
        "4x": ["fighting", "steel"],
    },
    "ice_steel": {
        "0x": ["poison"],
        "1/2x": ["normal", "grass", "flying", "psychic", "bug", "dragon", "fairy"],
        "1/4x": ["ice"],
        "1x": ["water", "electric", "rock", "ghost", "dark", "steel"],
        "2x": ["ground"],
        "4x": ["fire", "fighting"],
    },
    "ice_water": {
        "1/2x": ["water"],
        "1/4x": ["ice"],
        "1x": [
            "normal",
            "fire",
            "poison",
            "ground",
            "flying",
            "psychic",
            "bug",
            "ghost",
            "dragon",
            "dark",
            "steel",
            "fairy",
        ],
        "2x": ["electric", "grass", "fighting", "rock"],
    },
    "normal_dragon": {
        "0x": ["ghost"],
        "1/2x": ["fire", "water", "electric", "grass"],
        "1x": [
            "normal",
            "poison",
            "ground",
            "flying",
            "psychic",
            "bug",
            "rock",
            "dark",
            "steel",
        ],
        "2x": ["ice", "fighting", "dragon", "fairy"],
    },
    "normal_fairy": {
        "0x": ["ghost", "dragon"],
        "1/2x": ["bug", "dark"],
        "1x": [
            "normal",
            "fire",
            "water",
            "electric",
            "grass",
            "ice",
            "fighting",
            "ground",
            "flying",
            "psychic",
            "rock",
            "fairy",
        ],
        "2x": ["poison", "steel"],
    },
    "normal_fighting": {
        "0x": ["ghost"],
        "1/2x": ["bug", "rock", "dark"],
        "1x": [
            "normal",
            "fire",
            "water",
            "electric",
            "grass",
            "ice",
            "poison",
            "ground",
            "dragon",
            "steel",
        ],
        "2x": ["fighting", "flying", "psychic", "fairy"],
    },
    "normal_flying": {
        "0x": ["ground", "ghost"],
        "1/2x": ["grass", "bug"],
        "1x": [
            "normal",
            "fire",
            "water",
            "fighting",
            "poison",
            "flying",
            "psychic",
            "dragon",
            "dark",
            "steel",
            "fairy",
        ],
        "2x": ["electric", "ice", "rock"],
    },
    "normal_ghost": {
        "0x": ["normal", "fighting", "ghost"],
        "1/2x": ["poison", "bug"],
        "1x": [
            "fire",
            "water",
            "electric",
            "grass",
            "ice",
            "ground",
            "flying",
            "psychic",
            "rock",
            "dragon",
            "steel",
            "fairy",
        ],
        "2x": ["dark"],
    },
    "normal_grass": {
        "0x": ["ghost"],
        "1/2x": ["water", "electric", "grass", "ground"],
        "1x": ["normal", "psychic", "rock", "dragon", "dark", "steel", "fairy"],
        "2x": ["fire", "ice", "fighting", "poison", "flying", "bug"],
    },
    "normal_ground": {
        "0x": ["electric", "ghost"],
        "1/2x": ["poison", "rock"],
        "1x": [
            "normal",
            "fire",
            "ground",
            "flying",
            "psychic",
            "bug",
            "dragon",
            "dark",
            "steel",
            "fairy",
        ],
        "2x": ["water", "grass", "ice", "fighting"],
    },
    "normal_psychic": {
        "0x": ["ghost"],
        "1/2x": ["psychic"],
        "1x": [
            "normal",
            "fire",
            "water",
            "electric",
            "grass",
            "ice",
            "fighting",
            "poison",
            "ground",
            "flying",
            "rock",
            "dragon",
            "steel",
            "fairy",
        ],
        "2x": ["bug", "dark"],
    },
    "normal_water": {
        "0x": ["ghost"],
        "1/2x": ["fire", "water", "ice", "steel"],
        "1x": [
            "normal",
            "poison",
            "ground",
            "flying",
            "psychic",
            "bug",
            "rock",
            "dragon",
            "dark",
            "fairy",
        ],
        "2x": ["electric", "grass", "fighting"],
    },
    "poison_bug": {
        "1/2x": ["poison", "bug", "fairy"],
        "1/4x": ["grass", "fighting"],
        "1x": [
            "normal",
            "water",
            "electric",
            "ice",
            "ground",
            "ghost",
            "dragon",
            "dark",
            "steel",
        ],
        "2x": ["fire", "flying", "psychic", "rock"],
    },
    "poison_dark": {
        "0x": ["psychic"],
        "1/2x": ["grass", "poison", "ghost", "dark"],
        "1x": [
            "normal",
            "fire",
            "water",
            "electric",
            "ice",
            "fighting",
            "flying",
            "bug",
            "rock",
            "dragon",
            "steel",
            "fairy",
        ],
        "2x": ["ground"],
    },
    "poison_dragon": {
        "1/2x": ["fire", "water", "electric", "fighting", "poison", "bug"],
        "1/4x": ["grass"],
        "1x": ["normal", "flying", "rock", "ghost", "dark", "steel", "fairy"],
        "2x": ["ice", "ground", "psychic", "dragon"],
    },
    "poison_fairy": {
        "0x": ["dragon"],
        "1/2x": ["grass", "dark", "fairy"],
        "1/4x": ["fighting", "bug"],
        "1x": [
            "normal",
            "fire",
            "water",
            "electric",
            "ice",
            "poison",
            "flying",
            "rock",
            "ghost",
        ],
        "2x": ["ground", "psychic", "steel"],
    },
    "poison_fighting": {
        "1/2x": ["grass", "fighting", "poison", "rock", "dark"],
        "1/4x": ["bug"],
        "1x": [
            "normal",
            "fire",
            "water",
            "electric",
            "ice",
            "ghost",
            "dragon",
            "steel",
            "fairy",
        ],
        "2x": ["ground", "flying"],
        "4x": ["psychic"],
    },
    "poison_fire": {
        "1/2x": ["fire", "ice", "fighting", "poison", "steel"],
        "1/4x": ["grass", "bug", "fairy"],
        "1x": ["normal", "electric", "flying", "ghost", "dragon", "dark"],
        "2x": ["water", "psychic", "rock"],
        "4x": ["ground"],
    },
    "poison_flying": {
        "0x": ["ground"],
        "1/2x": ["poison", "fairy"],
        "1/4x": ["grass", "fighting", "bug"],
        "1x": ["normal", "fire", "water", "flying", "ghost", "dragon", "dark", "steel"],
        "2x": ["electric", "ice", "psychic", "rock"],
    },
    "poison_ghost": {
        "0x": ["normal", "fighting"],
        "1/2x": ["grass", "fairy"],
        "1/4x": ["poison", "bug"],
        "1x": ["fire", "water", "electric", "ice", "flying", "rock", "dragon", "steel"],
        "2x": ["ground", "psychic", "ghost", "dark"],
    },
    "poison_ground": {
        "0x": ["electric"],
        "1/2x": ["fighting", "bug", "rock", "fairy"],
        "1/4x": ["poison"],
        "1x": ["normal", "fire", "grass", "flying", "ghost", "dragon", "dark", "steel"],
        "2x": ["water", "ice", "ground", "psychic"],
    },
    "poison_normal": {
        "0x": ["ghost"],
        "1/2x": ["grass", "poison", "bug", "fairy"],
        "1x": [
            "normal",
            "fire",
            "water",
            "electric",
            "ice",
            "fighting",
            "flying",
            "rock",
            "dragon",
            "dark",
            "steel",
        ],
        "2x": ["ground", "psychic"],
    },
    "poison_psychic": {
        "1/2x": ["grass", "poison", "fairy"],
        "1/4x": ["fighting"],
        "1x": [
            "normal",
            "fire",
            "water",
            "electric",
            "ice",
            "flying",
            "psychic",
            "bug",
            "rock",
            "dragon",
            "steel",
        ],
        "2x": ["ground", "ghost", "dark"],
    },
    "poison_water": {
        "1/2x": ["fire", "water", "ice", "fighting", "poison", "bug", "steel", "fairy"],
        "1x": ["normal", "grass", "flying", "rock", "ghost", "dragon", "dark"],
        "2x": ["electric", "ground", "psychic"],
    },
    "psychic_dark": {
        "0x": ["psychic"],
        "1x": [
            "normal",
            "fire",
            "water",
            "electric",
            "grass",
            "ice",
            "fighting",
            "poison",
            "ground",
            "flying",
            "rock",
            "ghost",
            "dragon",
            "dark",
            "steel",
        ],
        "2x": ["fairy"],
        "4x": ["bug"],
    },
    "psychic_dragon": {
        "1/2x": ["fire", "water", "electric", "grass", "fighting", "psychic"],
        "1x": ["normal", "poison", "ground", "flying", "rock", "steel"],
        "2x": ["ice", "bug", "ghost", "dragon", "dark", "fairy"],
    },
    "psychic_fairy": {
        "0x": ["dragon"],
        "1/2x": ["psychic"],
        "1/4x": ["fighting"],
        "1x": [
            "normal",
            "fire",
            "water",
            "electric",
            "grass",
            "ice",
            "ground",
            "flying",
            "bug",
            "rock",
            "dark",
            "fairy",
        ],
        "2x": ["poison", "ghost", "steel"],
    },
    "psychic_fighting": {
        "1/2x": ["fighting", "rock"],
        "1x": [
            "normal",
            "fire",
            "water",
            "electric",
            "grass",
            "ice",
            "poison",
            "ground",
            "psychic",
            "bug",
            "dragon",
            "dark",
            "steel",
        ],
        "2x": ["flying", "ghost", "fairy"],
    },
    "psychic_fire": {
        "1/2x": ["fire", "grass", "ice", "fighting", "psychic", "steel", "fairy"],
        "1x": ["normal", "electric", "poison", "flying", "bug", "dragon"],
        "2x": ["water", "ground", "rock", "ghost", "dark"],
    },
    "psychic_flying": {
        "0x": ["ground"],
        "1/2x": ["grass", "psychic"],
        "1/4x": ["fighting"],
        "1x": [
            "normal",
            "fire",
            "water",
            "poison",
            "flying",
            "bug",
            "dragon",
            "steel",
            "fairy",
        ],
        "2x": ["electric", "ice", "rock", "ghost", "dark"],
    },
    "psychic_ghost": {
        "0x": ["normal", "fighting"],
        "1/2x": ["poison", "psychic"],
        "1x": [
            "fire",
            "water",
            "electric",
            "grass",
            "ice",
            "ground",
            "flying",
            "bug",
            "rock",
            "dragon",
            "steel",
            "fairy",
        ],
        "4x": ["ghost", "dark"],
    },
    "psychic_grass": {
        "1/2x": ["water", "electric", "grass", "fighting", "ground", "psychic"],
        "1x": ["normal", "rock", "dragon", "steel", "fairy"],
        "2x": ["fire", "ice", "poison", "flying", "ghost", "dark"],
        "4x": ["bug"],
    },
    "psychic_ice": {
        "1/2x": ["ice", "psychic"],
        "1x": [
            "normal",
            "water",
            "electric",
            "grass",
            "fighting",
            "poison",
            "ground",
            "flying",
            "dragon",
            "fairy",
        ],
        "2x": ["fire", "bug", "rock", "ghost", "dark", "steel"],
    },
    "psychic_normal": {
        "0x": ["ghost"],
        "1/2x": ["psychic"],
        "1x": [
            "normal",
            "fire",
            "water",
            "electric",
            "grass",
            "ice",
            "fighting",
            "poison",
            "ground",
            "flying",
            "rock",
            "dragon",
            "steel",
            "fairy",
        ],
        "2x": ["bug", "dark"],
    },
    "psychic_steel": {
        "0x": ["poison"],
        "1/2x": [
            "normal",
            "grass",
            "ice",
            "flying",
            "rock",
            "dragon",
            "steel",
            "fairy",
        ],
        "1/4x": ["psychic"],
        "1x": ["water", "electric", "fighting", "bug"],
        "2x": ["fire", "ground", "ghost", "dark"],
    },
    "rock_bug": {
        "1/2x": ["normal", "poison"],
        "1x": [
            "fire",
            "electric",
            "grass",
            "ice",
            "fighting",
            "ground",
            "flying",
            "psychic",
            "bug",
            "ghost",
            "dragon",
            "dark",
            "fairy",
        ],
        "2x": ["water", "rock", "steel"],
    },
    "rock_dark": {
        "0x": ["psychic"],
        "1/2x": ["normal", "fire", "poison", "flying", "ghost", "dark"],
        "1x": ["electric", "ice", "rock", "dragon"],
        "2x": ["water", "grass", "ground", "bug", "steel", "fairy"],
        "4x": ["fighting"],
    },
    "rock_dragon": {
        "1/2x": ["normal", "electric", "poison", "flying"],
        "1/4x": ["fire"],
        "1x": ["water", "grass", "psychic", "bug", "rock", "ghost", "dark"],
        "2x": ["ice", "fighting", "ground", "dragon", "steel", "fairy"],
    },
    "rock_electric": {
        "1/2x": ["normal", "fire", "electric", "poison"],
        "1/4x": ["flying"],
        "1x": [
            "ice",
            "psychic",
            "bug",
            "rock",
            "ghost",
            "dragon",
            "dark",
            "steel",
            "fairy",
        ],
        "2x": ["water", "grass", "fighting"],
        "4x": ["ground"],
    },
    "rock_fairy": {
        "0x": ["dragon"],
        "1/2x": ["normal", "fire", "flying", "bug", "dark"],
        "1x": [
            "electric",
            "ice",
            "fighting",
            "poison",
            "psychic",
            "rock",
            "ghost",
            "fairy",
        ],
        "2x": ["water", "grass", "ground"],
        "4x": ["steel"],
    },
    "rock_fighting": {
        "1/2x": ["normal", "fire", "poison", "bug", "rock", "dark"],
        "1x": ["electric", "ice", "flying", "ghost", "dragon"],
        "2x": ["water", "grass", "fighting", "ground", "psychic", "steel", "fairy"],
    },
    "rock_fire": {
        "1/2x": ["normal", "ice", "poison", "flying", "bug", "fairy"],
        "1/4x": ["fire"],
        "1x": ["electric", "grass", "psychic", "ghost", "dragon", "dark", "steel"],
        "2x": ["fighting", "rock"],
        "4x": ["water", "ground"],
    },
    "rock_flying": {
        "0x": ["ground"],
        "1/2x": ["normal", "fire", "poison", "flying", "bug"],
        "1x": ["grass", "fighting", "psychic", "ghost", "dragon", "dark", "fairy"],
        "2x": ["water", "electric", "ice", "rock", "steel"],
    },
    "rock_grass": {
        "1/2x": ["normal", "electric"],
        "1x": [
            "fire",
            "water",
            "grass",
            "poison",
            "ground",
            "flying",
            "psychic",
            "rock",
            "ghost",
            "dragon",
            "dark",
            "fairy",
        ],
        "2x": ["ice", "fighting", "bug", "steel"],
    },
    "rock_ground": {
        "0x": ["electric"],
        "1/2x": ["normal", "fire", "flying", "rock"],
        "1/4x": ["poison"],
        "1x": ["psychic", "bug", "ghost", "dragon", "dark", "fairy"],
        "2x": ["ice", "fighting", "ground", "steel"],
        "4x": ["water", "grass"],
    },
    "rock_ice": {
        "1/2x": ["normal", "ice", "poison", "flying"],
        "1x": [
            "fire",
            "electric",
            "psychic",
            "bug",
            "ghost",
            "dragon",
            "dark",
            "fairy",
        ],
        "2x": ["water", "grass", "ground", "rock"],
        "4x": ["fighting", "steel"],
    },
    "rock_poison": {
        "1/2x": ["normal", "fire", "flying", "bug", "fairy"],
        "1/4x": ["poison"],
        "1x": [
            "electric",
            "grass",
            "ice",
            "fighting",
            "rock",
            "ghost",
            "dragon",
            "dark",
        ],
        "2x": ["water", "psychic", "steel"],
        "4x": ["ground"],
    },
    "rock_psychic": {
        "1/2x": ["normal", "fire", "poison", "flying", "psychic"],
        "1x": ["electric", "ice", "fighting", "rock", "dragon", "fairy"],
        "2x": ["water", "grass", "ground", "bug", "ghost", "dark", "steel"],
    },
    "rock_steel": {
        "0x": ["poison"],
        "1/2x": ["ice", "psychic", "bug", "rock", "dragon", "fairy"],
        "1/4x": ["normal", "flying"],
        "1x": ["fire", "electric", "grass", "ghost", "dark", "steel"],
        "2x": ["water"],
        "4x": ["fighting", "ground"],
    },
    "rock_water": {
        "1/2x": ["normal", "ice", "poison", "flying"],
        "1/4x": ["fire"],
        "1x": [
            "water",
            "psychic",
            "bug",
            "rock",
            "ghost",
            "dragon",
            "dark",
            "steel",
            "fairy",
        ],
        "2x": ["electric", "fighting", "ground"],
        "4x": ["grass"],
    },
    "steel_dragon": {
        "0x": ["poison"],
        "1/2x": [
            "normal",
            "water",
            "electric",
            "flying",
            "psychic",
            "bug",
            "rock",
            "steel",
        ],
        "1/4x": ["grass"],
        "1x": ["fire", "ice", "ghost", "dragon", "dark", "fairy"],
        "2x": ["fighting", "ground"],
    },
    "steel_fairy": {
        "0x": ["poison", "dragon"],
        "1/2x": [
            "normal",
            "grass",
            "ice",
            "flying",
            "psychic",
            "rock",
            "dark",
            "fairy",
        ],
        "1/4x": ["bug"],
        "1x": ["water", "electric", "fighting", "ghost", "steel"],
        "2x": ["fire", "ground"],
    },
    "steel_fighting": {
        "0x": ["poison"],
        "1/2x": ["normal", "grass", "ice", "dragon", "dark", "steel"],
        "1/4x": ["bug", "rock"],
        "1x": ["water", "electric", "flying", "psychic", "ghost", "fairy"],
        "2x": ["fire", "fighting", "ground"],
    },
    "steel_flying": {
        "0x": ["poison", "ground"],
        "1/2x": ["normal", "flying", "psychic", "dragon", "steel", "fairy"],
        "1/4x": ["grass", "bug"],
        "1x": ["water", "ice", "fighting", "rock", "ghost", "dark"],
        "2x": ["fire", "electric"],
    },
    "steel_ghost": {
        "0x": ["normal", "fighting", "poison"],
        "1/2x": [
            "grass",
            "ice",
            "flying",
            "psychic",
            "rock",
            "dragon",
            "steel",
            "fairy",
        ],
        "1/4x": ["bug"],
        "1x": ["water", "electric"],
        "2x": ["fire", "ground", "ghost", "dark"],
    },
    "steel_ground": {
        "0x": ["electric", "poison"],
        "1/2x": ["normal", "flying", "psychic", "bug", "dragon", "steel", "fairy"],
        "1/4x": ["rock"],
        "1x": ["grass", "ice", "ghost", "dark"],
        "2x": ["fire", "water", "fighting", "ground"],
    },
    "steel_poison": {
        "0x": ["poison"],
        "1/2x": ["normal", "ice", "flying", "rock", "dragon", "steel"],
        "1/4x": ["grass", "bug", "fairy"],
        "1x": ["water", "electric", "fighting", "psychic", "ghost", "dark"],
        "2x": ["fire"],
        "4x": ["ground"],
    },
    "steel_psychic": {
        "0x": ["poison"],
        "1/2x": [
            "normal",
            "grass",
            "ice",
            "flying",
            "rock",
            "dragon",
            "steel",
            "fairy",
        ],
        "1/4x": ["psychic"],
        "1x": ["water", "electric", "fighting", "bug"],
        "2x": ["fire", "ground", "ghost", "dark"],
    },
    "steel_rock": {
        "0x": ["poison"],
        "1/2x": ["ice", "psychic", "bug", "rock", "dragon", "fairy"],
        "1/4x": ["normal", "flying"],
        "1x": ["fire", "electric", "grass", "ghost", "dark", "steel"],
        "2x": ["water"],
        "4x": ["fighting", "ground"],
    },
    "water_bug": {
        "1/2x": ["water", "ice", "fighting", "ground", "steel"],
        "1x": [
            "normal",
            "fire",
            "grass",
            "poison",
            "psychic",
            "bug",
            "ghost",
            "dragon",
            "dark",
            "fairy",
        ],
        "2x": ["electric", "flying", "rock"],
    },
    "water_dark": {
        "0x": ["psychic"],
        "1/2x": ["fire", "water", "ice", "ghost", "dark", "steel"],
        "1x": ["normal", "poison", "ground", "flying", "rock", "dragon"],
        "2x": ["electric", "grass", "fighting", "bug", "fairy"],
    },
    "water_dragon": {
        "1/2x": ["steel"],
        "1/4x": ["fire", "water"],
        "1x": [
            "normal",
            "electric",
            "grass",
            "ice",
            "fighting",
            "poison",
            "ground",
            "flying",
            "psychic",
            "bug",
            "rock",
            "ghost",
            "dark",
        ],
        "2x": ["dragon", "fairy"],
    },
    "water_electric": {
        "1/2x": ["fire", "water", "ice", "flying"],
        "1/4x": ["steel"],
        "1x": [
            "normal",
            "electric",
            "fighting",
            "poison",
            "psychic",
            "bug",
            "rock",
            "ghost",
            "dragon",
            "dark",
            "fairy",
        ],
        "2x": ["grass", "ground"],
    },
    "water_fairy": {
        "0x": ["dragon"],
        "1/2x": ["fire", "water", "ice", "fighting", "bug", "dark"],
        "1x": [
            "normal",
            "ground",
            "flying",
            "psychic",
            "rock",
            "ghost",
            "steel",
            "fairy",
        ],
        "2x": ["electric", "grass", "poison"],
    },
    "water_fighting": {
        "1/2x": ["fire", "water", "ice", "bug", "rock", "dark", "steel"],
        "1x": ["normal", "fighting", "poison", "ground", "ghost", "dragon"],
        "2x": ["electric", "grass", "flying", "psychic", "fairy"],
    },
    "water_flying": {
        "0x": ["ground"],
        "1/2x": ["fire", "water", "fighting", "bug", "steel"],
        "1x": [
            "normal",
            "grass",
            "ice",
            "poison",
            "flying",
            "psychic",
            "ghost",
            "dragon",
            "dark",
            "fairy",
        ],
        "2x": ["rock"],
        "4x": ["electric"],
    },
    "water_ghost": {
        "0x": ["normal", "fighting"],
        "1/2x": ["fire", "water", "ice", "poison", "bug", "steel"],
        "1x": ["ground", "flying", "psychic", "rock", "dragon", "fairy"],
        "2x": ["electric", "grass", "ghost", "dark"],
    },
    "water_grass": {
        "1/2x": ["ground", "steel"],
        "1/4x": ["water"],
        "1x": [
            "normal",
            "fire",
            "electric",
            "grass",
            "ice",
            "fighting",
            "psychic",
            "rock",
            "ghost",
            "dragon",
            "dark",
            "fairy",
        ],
        "2x": ["poison", "flying", "bug"],
    },
    "water_ground": {
        "0x": ["electric"],
        "1/2x": ["fire", "poison", "rock", "steel"],
        "1x": [
            "normal",
            "water",
            "ice",
            "fighting",
            "ground",
            "flying",
            "psychic",
            "bug",
            "ghost",
            "dragon",
            "dark",
            "fairy",
        ],
        "4x": ["grass"],
    },
    "water_ice": {
        "1/2x": ["water"],
        "1/4x": ["ice"],
        "1x": [
            "normal",
            "fire",
            "poison",
            "ground",
            "flying",
            "psychic",
            "bug",
            "ghost",
            "dragon",
            "dark",
            "steel",
            "fairy",
        ],
        "2x": ["electric", "grass", "fighting", "rock"],
    },
    "water_poison": {
        "1/2x": ["fire", "water", "ice", "fighting", "poison", "bug", "steel", "fairy"],
        "1x": ["normal", "grass", "flying", "rock", "ghost", "dragon", "dark"],
        "2x": ["electric", "ground", "psychic"],
    },
    "water_psychic": {
        "1/2x": ["fire", "water", "ice", "fighting", "psychic", "steel"],
        "1x": ["normal", "poison", "ground", "flying", "rock", "dragon", "fairy"],
        "2x": ["electric", "grass", "bug", "ghost", "dark"],
    },
    "water_rock": {
        "1/2x": ["normal", "ice", "poison", "flying"],
        "1/4x": ["fire"],
        "1x": [
            "water",
            "psychic",
            "bug",
            "rock",
            "ghost",
            "dragon",
            "dark",
            "steel",
            "fairy",
        ],
        "2x": ["electric", "fighting", "ground"],
        "4x": ["grass"],
    },
    "water_steel": {
        "0x": ["poison"],
        "1/2x": [
            "normal",
            "water",
            "flying",
            "psychic",
            "bug",
            "rock",
            "dragon",
            "fairy",
        ],
        "1/4x": ["ice", "steel"],
        "1x": ["fire", "grass", "ghost", "dark"],
        "2x": ["electric", "fighting", "ground"],
    },
}
