class HATT_KEYWORDS:
    safari_zone = [
        "safari",
        "sz",
        "safari balls",
        "bait",
        "rocks",
        "steps",
        "registration requirements",
        "entry fee",
        "safari ticket",
        "pokecoins",
        "patreon tokens",
        "vote coins",
        "runs per day",
        "promo perks",
        "rare spawns",
        "spiky-eared pichu",
        "tauros",
        "kangaskhan",
        "girafarig",
        "tropius",
        "starters",
        "bulbasaur",
        "charmander",
        "chikorita",
        "cyndaquil",
        "totodile",
        "gyms",
        "elite four",
        "champions",
        "non-default icon",
        "spawn rate",
    ]

    safari_zone_secrets = [
        "sz",
        "safari",
        # 🏃 Movement / Unlockables
        "running shoes",
        "speed boost",
        "teleport waypoint",
        "warp",
        # 🧑 NPCs
        "gopi",
        # 📦 Hidden Mechanics
        "inspect box",
        "pokeball box",
        "poke ball box",
        "fastball",
        "heavyball",
        "quickball",
        # 🗺️ Secret Locations
        "map 3",
        "bridge",
        "starting point",
        "cave",
        # 🐾 Special Spawns
        "abra",
    ]
